# Generated by Django 4.2.7 on 2024-04-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='featured_image',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
    ]
