# Generated by Django 4.2.7 on 2024-04-28 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0002_person_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appblog.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='static/images'),
        ),
    ]
