# Generated by Django 4.2.7 on 2024-05-02 06:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appblog', '0004_person_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Message',
        ),
    ]
